controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    eureka_controller:
      type: eureka/RobotController


eureka_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6a
      - joint6b

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
